### ISSUE TITLE
Adresse du site tier

### ISSUE THREAD

**Issue by BlueSelune** [octetsetquartdepouces/mushraider_phpbb_bridge#2]
Bonjour.

Nulle part dans les paramètres du mod phpbb je ne trouve l'adresse du site tier à utiliser pour la configuration sur Mushraider.
J'ai essayé quelques URL mais rien n'y fait, tout est rejeté.
Merci de votre aide !

**Comment by Kyah** [comment]
Arf j'avais zappé totalement cette issue, je vais voir si je suis en mesure de générer la ligne de configuration qui va bien pour que ce soit facile pour tout le monde :+1:

**Comment by BlueSelune** [comment]
J'ai trouvé l'URL entre temps. Tout a parfaitement fonctionné (jusqu'à notre migration récente vers phpBB 3.1)

**Comment by Kyah** [comment]
Traité tout de même dans 15db8c4c1fac9825c2a082b6dfabf9747837147f
