### ISSUE TITLE
phpBB 3.1 Extensions system compatibility

### ISSUE THREAD

**Issue by olbat** [octetsetquartdepouces/mushraider_phpbb_bridge#3]
Apparently the phpBB module's API has changed in the [version 3.1](https://wiki.phpbb.com/PhpBB3.1), it makes the module unusable with up-to-date phpBB boards ...

Will it be possible to update the module in order to be compatible with the [new Extension API](https://wiki.phpbb.com/Category:Extensions) ?

If needed, [here is some documentation](https://www.phpbb.com/community/viewtopic.php?f=461&t=2211266) about the migration procedure.

**Comment by Kyah** [comment]
Done here : https://github.com/octetsetquartdepouces/phpbb-ext-mushraider
